<a href="https://colab.research.google.com/github/Pallab18/tensorflow_notebooks/blob/notebooks/TF_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Tensors

In [1]:
import tensorflow as tf

In [2]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
tf.__version__

'2.5.0'

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector1 = tf.constant([[10, 10], [20, 10]])

In [8]:
vector1 = tf.constant([[10, 10], [20, 10], [30, 20]])

In [9]:
vector1.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 10],
       [30, 20]], dtype=int32)>>

In [10]:
vector.ndim

1

# Mutable and Immutable Variables

In [11]:
a=tf.Variable(2.)

In [12]:
a.assign(3)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=3.0>

In [13]:
a

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [14]:
changeable_tensor=tf.Variable([10, 7])
nonchangeable_tensor=tf.constant([10, 7])

In [15]:
changeable_tensor, nonchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Random Tensors

In [17]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))

random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))

random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
not_shuffle = tf.constant([[10, 7], [3, 4], [2, 5]])

In [19]:
not_shuffle.ndim

2

In [20]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Numpy array to Tensors

In [22]:
import numpy as np

In [23]:
numpy_arr = np.arange(1, 25, dtype=np.int32)

In [24]:
tf.constant(numpy_arr)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [25]:
tf.constant(numpy_arr, shape=(3, 2, 4))

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [26]:
var1 = tf.Variable(numpy_arr)

In [27]:
var1[0].assign(-110)

<tf.Variable 'UnreadVariable' shape=(24,) dtype=int32, numpy=
array([-110,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24], dtype=int32)>

# Getting info from tensors

In [28]:
new_tensor = tf.Variable([[1,2],[3,4]])

In [29]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

# Tensors Indexing

In [36]:
# first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# various info

print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor))

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
tf.Tensor(120, shape=(), dtype=int32)


In [41]:
# rank_4_tensor

In [38]:
 # get the first element of each dimension from each index except for the final one

 rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
# create a rank 2 tensor

rank_2_tensor = tf.ones(shape=[2, 2])

In [44]:
#get the last item of each row

rank_new = rank_2_tensor[:, -1]

In [45]:
rank_new

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [47]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
 array([[[1.],
         [1.]],
 
        [[1.],
         [1.]]], dtype=float32)>)

In [53]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]]], dtype=float32)>